version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp

  loki:
    image: grafana/loki:main
    command: '-config.file=/etc/loki/loki-config.yaml'
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml

  faro_collector:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
      - 3333:3333
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - tempo

  init_tempo:
    image: &tempo_image grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempo_image
    ports:
      - 3200:3200
      - 4318:4318
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml 
      - ./tempo-data:/var/tempo

    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      - init_tempo
